#!/usr/bin/env python3
"""Put the lab's own colours and mark on the hosted sign in screens.

A member goes from the members portal to these screens to type their password
and comes back. If the screens are somebody else's, that walk reads as leaving
the lab's site at the one moment a person is asked to trust it.

Split out of api.py because it is a concern of its own, and because the asset
upload is a multipart request and everything else in api.py is JSON.

Two things this could not close, and both are written down rather than left to
be discovered:

The typeface. packages/gantry-tokens/tokens.css names Archivo, Instrument Sans,
IBM Plex Mono and Charis SIL, and ships none of them, so the portal itself falls
back to whatever the machine has. Zitadel can be handed a font file and there is
no font file here to hand it.

The hazard band and the layout. The label policy carries colours, a logo, an
icon and a font. It does not carry a page.
"""
from __future__ import annotations

import pathlib
import secrets
import urllib.error
import urllib.request

import api

ROOT = pathlib.Path(__file__).resolve().parents[2]
LOCKUP = ROOT / "packages/gantry-tokens/brand/hsl-lockup.svg"

# Every value read from packages/gantry-tokens/tokens.css and named beside it so
# a change there can be followed here.
POLICY = {
    "primaryColor":        "#97600c",   # --accent-text, light. --hazard itself
                                        # is too pale to read on paper
    "backgroundColor":     "#f4efe3",   # --char, light
    "warnColor":           "#b8341f",   # --fault, light
    "fontColor":           "#1c1812",   # --bone, light
    "primaryColorDark":    "#f2ab1e",   # --hazard, dark
    "backgroundColorDark": "#15120f",   # --char, dark
    "warnColorDark":       "#d24f3a",   # --fault, dark
    "fontColorDark":       "#ece3d3",   # --bone, dark
    # A member signs in with an email address, and the organisation suffix
    # Zitadel appends to a login name is not part of it.
    "hideLoginNameSuffix": True,
    "disableWatermark": True,
    # Light, and not the AUTO that Zitadel defaults to. The portal sets no
    # data-theme, and tokens.css says a page that sets none is light, so the
    # portal is light whatever the machine prefers. Left on AUTO these screens
    # follow the machine instead, and a member on a dark desktop walked from a
    # cream page to a black one and back. Measured on 2026-08-31.
    "themeMode": "THEME_MODE_LIGHT",
}


def upload(path: str, blob: bytes, token: str) -> tuple[int, str]:
    """One multipart POST to the assets API, which takes no JSON."""
    boundary = "----oro" + secrets.token_hex(16)
    body = b"".join([
        ('--%s\r\nContent-Disposition: form-data; name="file"; '
         'filename="%s"\r\nContent-Type: image/svg+xml\r\n\r\n'
         % (boundary, LOCKUP.name)).encode(),
        blob,
        ("\r\n--%s--\r\n" % boundary).encode(),
    ])
    request = urllib.request.Request(
        api.BASE + path, data=body, method="POST",
        headers={"Authorization": "Bearer " + token,
                 "Content-Type": "multipart/form-data; boundary=" + boundary})
    try:
        with urllib.request.urlopen(request) as answer:
            return answer.status, ""
    except urllib.error.HTTPError as refused:
        return refused.code, refused.read().decode(errors="replace")[:200]


def apply_branding(token: str) -> None:
    """Set the policy, upload the mark, and activate.

    Activation is separate and it is the half that is easy to miss: a policy
    that is set and never activated is stored, readable, and changes nothing on
    the screens a member sees. The upload needs it too, so it comes last.
    """
    answer = api.call("/management/v1/policies/label", POLICY, token)
    if answer.status != 200:
        answer = api.call("/management/v1/policies/label", POLICY, token,
                          method="PUT")
    if answer.status != 200 and "not been changed" not in answer.message():
        raise SystemExit(f"branding: {answer.status} {answer.message()}")

    if not LOCKUP.exists():
        raise SystemExit(
            f"branding: {LOCKUP} is missing, so the sign in screens would carry "
            "the lab's colours and no mark. It is generated by "
            "packages/gantry-tokens/brand/build-the-lockup.py from the same two "
            "SVGs the portal masthead carries.")
    blob = LOCKUP.read_bytes()
    # The logo sits above the sign in card. The icon is the same lockup because
    # there is one mark, and Zitadel falls back to its own where a slot is empty.
    for slot in ("logo", "icon", "logo/dark", "icon/dark"):
        status, said = upload(f"/assets/v1/org/policy/label/{slot}", blob, token)
        if status != 200:
            raise SystemExit(f"branding: the {slot} was refused: {status} {said}")

    activated = api.call("/management/v1/policies/label/_activate", {}, token)
    if activated.status != 200:
        raise SystemExit(f"branding could not be activated: "
                         f"{activated.status} {activated.message()}")
    print("branding: colours, mark and light theme applied and activated")
