#!/usr/bin/env python3
"""Prove the attributions generator refuses what it cannot read.

A generator that has only ever been run on the two locks in this repository
proves nothing, because both are correct. Each check here builds a throwaway
lock and a stub of the metadata an image would have reported, plants one thing
in it, and asserts the generator reports that thing rather than writing a row
somebody would later cite.

    python3 tools/attributions/test_attributions.py

Needs python3 and nothing else. No docker, because the half that talks to
docker is four lines of subprocess and the half that decides every cell of the
table is here.
"""
from __future__ import annotations

import pathlib
import sys
import tempfile

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import dependency_table as table  # noqa: E402
import generate  # noqa: E402

LOCK_HEADER = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    uv pip compile --universal --generate-hashes --python-version 3.13 "
    "requirements.in -o requirements.txt\n"
)


def lock(*entries: str) -> str:
    """A lockfile in the shape uv writes, with the hash lines left out.

    The hashes are what pip enforces and they are not what this generator
    reads, so a lock carrying them would only make each check harder to read.
    """
    return LOCK_HEADER + "".join(f"{entry}\n    # via somebody\n" for entry in entries)


def stub(**packages) -> dict:
    """The JSON read_metadata.py writes, with the fields each check cares about."""
    built = {}
    for name, fields in packages.items():
        built[name.replace("_", "-")] = {
            "name": fields.get("display", name.replace("_", "-")),
            "version": fields.get("version", "1.0"),
            "license_expression": fields.get("expression"),
            "license_field": fields.get("field"),
            "classifiers": fields.get("classifiers", []),
            "requires": fields.get("requires", []),
        }
    return {"python_version": "3.13.15", "packages": built}


def build(lock_text: str, direct_text: str, metadata: dict) -> list[table.Row]:
    with tempfile.TemporaryDirectory() as directory:
        root = pathlib.Path(directory)
        (root / "requirements.txt").write_text(lock_text)
        (root / "requirements.in").write_text(direct_text)
        return table.rows_for(root / "requirements.txt", root / "requirements.in",
                              metadata)


def refusal(lock_text: str, direct_text: str, metadata: dict) -> str:
    try:
        build(lock_text, direct_text, metadata)
    except table.Refused as refused:
        return str(refused)
    raise AssertionError("nothing was refused")


def test_a_version_the_image_disagrees_with_is_refused():
    """The lock says one version and the image installed another.

    This is the row somebody would cite in three years, so a generator that
    quietly preferred one of the two numbers would be worse than no generator.
    """
    message = refusal(lock("fastapi==0.141.1"), "fastapi\n",
                      stub(fastapi={"expression": "MIT", "version": "0.140.0"}))
    assert "fastapi" in message, message
    assert "0.141.1" in message and "0.140.0" in message, message


def test_a_package_the_image_does_not_have_is_refused():
    message = refusal(lock("fastapi==0.141.1"), "fastapi\n", stub())
    assert "fastapi" in message, message
    assert "no metadata" in message, message


def test_a_package_the_lock_installs_elsewhere_is_reported_as_not_installed():
    """tzdata is the real case: the lock is universal and the image is Linux."""
    rows = build(
        lock("psycopg==3.3.4", "tzdata==2026.3 ; sys_platform == 'win32'"),
        "psycopg\n",
        stub(psycopg={"expression": "LGPL-3.0-only", "version": "3.3.4",
                      "requires": ['tzdata; sys_platform == "win32"']}))
    tzdata = [row for row in rows if row.name == "tzdata"][0]
    assert tzdata.licence_source == table.NOT_INSTALLED, tzdata
    assert "sys_platform == 'win32'" in tzdata.licence, tzdata
    assert tzdata.requesters == "psycopg", tzdata


def test_a_licence_field_is_used_when_there_is_no_expression():
    rows = build(lock("h11==0.16.0"), "h11\n",
                 stub(h11={"field": "MIT", "version": "0.16.0",
                           "classifiers": ["License :: OSI Approved :: MIT License"]}))
    assert rows[0].licence == "MIT", rows[0]
    assert rows[0].licence_source == "License", rows[0]


def test_a_classifier_is_the_fallback_when_neither_field_is_set():
    rows = build(lock("mdurl==0.1.2"), "mdurl\n",
                 stub(mdurl={"version": "0.1.2",
                             "classifiers": ["License :: OSI Approved :: MIT License"]}))
    assert rows[0].licence == "MIT", rows[0]
    assert rows[0].licence_source == table.CLASSIFIER, rows[0]


def test_a_pasted_licence_text_is_not_read_as_an_identifier():
    """Some packages put the whole licence in the field. It is not a name."""
    rows = build(lock("old==1.0"), "old\n",
                 stub(old={"field": "Copyright 2019 somebody.\n\nPermission is "
                                    "hereby granted, free of charge, to any "
                                    "person obtaining a copy of this software",
                           "classifiers": ["License :: OSI Approved :: MIT License"]}))
    assert rows[0].licence == "MIT", rows[0]
    assert rows[0].licence_source == table.CLASSIFIER, rows[0]


def test_a_package_recording_no_licence_at_all_is_refused():
    message = refusal(lock("silent==1.0"), "silent\n", stub(silent={}))
    assert "silent" in message, message
    assert "no licence" in message, message


def test_a_copyleft_licence_is_marked():
    rows = build(lock("psycopg==3.3.4"), "psycopg\n",
                 stub(psycopg={"expression": "LGPL-3.0-only", "version": "3.3.4"}))
    assert rows[0].licence == "**LGPL-3.0-only**", rows[0]


def test_an_extra_that_was_asked_for_is_named_in_the_requester():
    rows = build(lock("psycopg==3.3.4", "psycopg-binary==3.3.4"),
                 "psycopg[binary]\n",
                 stub(psycopg={"expression": "LGPL-3.0-only", "version": "3.3.4",
                               "requires": ['psycopg-binary==3.3.4; extra == "binary"']},
                      psycopg_binary={"expression": "LGPL-3.0-only", "version": "3.3.4"}))
    binary = [row for row in rows if row.name == "psycopg-binary"][0]
    assert binary.requesters == "psycopg[binary]", binary


def test_an_extra_nobody_asked_for_does_not_credit_a_requester():
    """The lock has the package for another reason, so the edge is not real."""
    rows = build(lock("pydantic==2.13.5", "tzdata==2026.3 ; sys_platform == 'win32'",
                      "psycopg==3.3.4"),
                 "pydantic\npsycopg\n",
                 stub(pydantic={"expression": "MIT", "version": "2.13.5",
                                "requires": ["tzdata; (python_version >= '3.9' and "
                                             "platform_system == 'Windows') and "
                                             "extra == 'timezone'"]},
                      psycopg={"expression": "LGPL-3.0-only", "version": "3.3.4",
                               "requires": ['tzdata; sys_platform == "win32"']}))
    tzdata = [row for row in rows if row.name == "tzdata"][0]
    assert tzdata.requesters == "psycopg", tzdata


def test_a_requirement_older_pythons_need_does_not_credit_a_requester():
    """The lock is compiled at 3.13, so `python_version < "3.13"` is never true.

    typing-extensions is the real case. Eleven packages name it and six of them
    name it only below the version this lock was compiled for, so a generator
    that ignored the marker would credit six requesters that did not ask.
    """
    rows = build(lock("starlette==1.6.0", "fastapi==0.141.1",
                      "typing-extensions==4.16.0"),
                 "fastapi\n",
                 stub(fastapi={"expression": "MIT", "version": "0.141.1",
                               "requires": ["starlette>=0.46.0",
                                            "typing-extensions>=4.8.0"]},
                      starlette={"expression": "BSD-3-Clause", "version": "1.6.0",
                                 "requires": ["typing-extensions>=4.10.0; "
                                              "python_version < '3.13'"]},
                      typing_extensions={"expression": "PSF-2.0", "version": "4.16.0"}))
    extensions = [row for row in rows if row.name == "typing-extensions"][0]
    assert extensions.requesters == "fastapi", extensions


def test_a_marker_that_cannot_be_read_is_refused():
    message = refusal(
        lock("fastapi==0.141.1", "idna==3.19"), "fastapi\n",
        stub(fastapi={"expression": "MIT", "version": "0.141.1",
                      "requires": ["idna>=2.8; sys_platform == 'linux' or "
                                   "python_version < '3.13'"]},
             idna={"expression": "BSD-3-Clause", "version": "3.19"}))
    assert "idna" in message, message
    assert "marker" in message, message


def test_a_lock_entry_nothing_asks_for_is_refused():
    message = refusal(lock("fastapi==0.141.1", "stowaway==9.9"), "fastapi\n",
                      stub(fastapi={"expression": "MIT", "version": "0.141.1"},
                           stowaway={"expression": "MIT", "version": "9.9"}))
    assert "stowaway" in message, message
    assert "nothing in the lock asks for it" in message, message


def test_a_direct_requirement_missing_from_the_lock_is_refused():
    message = refusal(lock("fastapi==0.141.1"), "fastapi\nuvicorn\n",
                      stub(fastapi={"expression": "MIT", "version": "0.141.1"}))
    assert "uvicorn" in message, message
    assert "requirements.in" in message, message


def test_a_lock_compiled_for_another_python_is_refused():
    metadata = stub(fastapi={"expression": "MIT", "version": "0.141.1"})
    metadata["python_version"] = "3.11.9"
    message = refusal(lock("fastapi==0.141.1"), "fastapi\n", metadata)
    assert "3.13" in message and "3.11" in message, message


def test_the_page_outside_the_markers_is_left_alone():
    with tempfile.TemporaryDirectory() as directory:
        page = pathlib.Path(directory) / "ATTRIBUTIONS.md"
        page.write_text("Hand written above.\n"
                        f"{generate.BEGIN}\nold table\n{generate.END}\n"
                        "Hand written below.\n")
        generate.splice(page, "new table")
        after = page.read_text()
        assert "Hand written above." in after, after
        assert "Hand written below." in after, after
        assert "old table" not in after, after
        assert "new table" in after, after


def test_the_read_date_alone_is_not_a_difference():
    """A clock is not a change, and this check went red on one.

    The page said 2026-08-30 while the generator, which stamps UTC, had reached
    2026-08-31, so --check reported a diff on a repository nobody had touched.
    The comparison runs against the date already on the page, and only a real
    difference moves it.
    """
    with tempfile.TemporaryDirectory() as directory:
        page = pathlib.Path(directory) / "ATTRIBUTIONS.md"
        region = "Read on 2020-01-01, out of an image built from `x/Dockerfile`."
        page.write_text(f"{generate.BEGIN}\n{region}\n{generate.END}\n")
        assert generate.date_on_the_page(page) == "2020-01-01"
        assert generate.region_matches(page, region)
        assert not generate.region_matches(page, region.replace("2020", "2021"))


def test_a_page_with_no_markers_is_refused():
    with tempfile.TemporaryDirectory() as directory:
        page = pathlib.Path(directory) / "ATTRIBUTIONS.md"
        page.write_text("Nothing marked here.\n")
        try:
            generate.splice(page, "new table")
        except table.Refused as refused:
            assert generate.BEGIN in str(refused), refused
            return
        raise AssertionError("a page with no markers was rewritten anyway")


def _run() -> int:
    checks = [(name, fn) for name, fn in sorted(globals().items())
              if name.startswith("test_") and callable(fn)]
    failed = []
    for name, fn in checks:
        try:
            fn()
        except AssertionError as exc:
            failed.append(name)
            print(f"FAIL {name}  {exc}")
        except Exception as exc:  # noqa: BLE001
            failed.append(name)
            print(f"ERROR {name}  {type(exc).__name__}: {exc}")
    print(f"\n{len(checks) - len(failed)}/{len(checks)} passed")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(_run())
